# Site settings
title: "Microbiome Innovation Theme Seminar"  # 网站标题，显示在浏览器标签页和网站顶部
description: "Microbiome Innovation Theme Seminar"  # 网站描述，一般用于搜索引擎结果显示

# Build settings
theme: jekyll-theme-minimal  # 主题设置，选择你喜欢的主题，也可以自己编写或者选择其他现成主题
markdown: kramdown  # Markdown解析器设置，可以使用kramdown或者其他支持的解析器
